"""werkzeuge

Revision: 1b8150487827
Vorherige: cf7557412e2e
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '1b8150487827'
down_revision = 'cf7557412e2e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('werkzeuge',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('typ', sa.String(length=32), nullable=False),
    sa.Column('beschreibung', sa.Text(), nullable=False),
    sa.Column('konfiguration', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('entdeckt', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('aktiv', sa.Boolean(), nullable=False),
    sa.Column('vorausgewaehlt', sa.Boolean(), nullable=False),
    sa.Column('zuletzt_geprueft', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pruefung', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('erstellt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('aktualisiert', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('werkzeuge')
    # ### end Alembic commands ###
