"""grundgeruest

Revision: cf7557412e2e
Vorherige: 
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

revision = 'cf7557412e2e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anbieter',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('typ', sa.String(length=32), nullable=False),
    sa.Column('art', sa.String(length=16), nullable=False),
    sa.Column('basis_url', sa.String(length=500), nullable=False),
    sa.Column('api_schluessel', sa.String(length=500), nullable=False),
    sa.Column('modell', sa.String(length=200), nullable=False),
    sa.Column('parameter', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('aktiv', sa.Boolean(), nullable=False),
    sa.Column('erstellt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('aktualisiert', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('einstellungen',
    sa.Column('schluessel', sa.String(length=120), nullable=False),
    sa.Column('wert', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('aktualisiert', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('schluessel')
    )
    op.create_table('quellen',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('typ', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('basis_url', sa.String(length=500), nullable=False),
    sa.Column('kanal_id', sa.String(length=100), nullable=False),
    sa.Column('kanal_name', sa.String(length=200), nullable=False),
    sa.Column('kanal_beschreibung', sa.Text(), nullable=False),
    sa.Column('regeln', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('aktiv', sa.Boolean(), nullable=False),
    sa.Column('zuletzt_abgeglichen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('erstellt', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('unterhaltungen',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('titel', sa.String(length=300), nullable=False),
    sa.Column('suchparameter', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('erstellt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('aktualisiert', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nachrichten',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('unterhaltung_id', sa.String(length=32), nullable=False),
    sa.Column('rolle', sa.String(length=16), nullable=False),
    sa.Column('inhalt', sa.Text(), nullable=False),
    sa.Column('stellen', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('parameter', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('modell', sa.String(length=200), nullable=False),
    sa.Column('dauer_ms', sa.Integer(), nullable=True),
    sa.Column('tokens_ein', sa.Integer(), nullable=True),
    sa.Column('tokens_aus', sa.Integer(), nullable=True),
    sa.Column('fehler', sa.Text(), nullable=False),
    sa.Column('erstellt', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['unterhaltung_id'], ['unterhaltungen.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_nachrichten_unterhaltung', 'nachrichten', ['unterhaltung_id'], unique=False)
    op.create_table('videos',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('quelle_id', sa.String(length=32), nullable=True),
    sa.Column('extern_id', sa.String(length=64), nullable=False),
    sa.Column('original_url', sa.String(length=500), nullable=False),
    sa.Column('titel', sa.Text(), nullable=False),
    sa.Column('beschreibung', sa.Text(), nullable=False),
    sa.Column('veroeffentlicht', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dauer_s', sa.Integer(), nullable=True),
    sa.Column('typ', sa.String(length=16), nullable=False),
    sa.Column('aufrufe', sa.Integer(), nullable=True),
    sa.Column('schlagworte', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('kanal_name', sa.String(length=200), nullable=False),
    sa.Column('serie', sa.String(length=32), nullable=False),
    sa.Column('folge_nr', sa.Integer(), nullable=True),
    sa.Column('miniatur_url', sa.String(length=600), nullable=False),
    sa.Column('miniatur_pfad', sa.String(length=500), nullable=False),
    sa.Column('metadaten_original', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('quelle_heruntergeladen', sa.Boolean(), nullable=False),
    sa.Column('ausgewaehlt', sa.Boolean(), nullable=False),
    sa.Column('auswahl_manuell', sa.Boolean(), nullable=False),
    sa.Column('stufe', sa.String(length=16), nullable=False),
    sa.Column('fehler', sa.Text(), nullable=False),
    sa.Column('prioritaet', sa.Integer(), nullable=False),
    sa.Column('notizen', sa.Text(), nullable=False),
    sa.Column('erstellt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('aktualisiert', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['quelle_id'], ['quellen.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('quelle_id', 'extern_id', name='uq_video_quelle_extern')
    )
    op.create_index('ix_videos_serie_folge', 'videos', ['serie', 'folge_nr'], unique=False)
    op.create_index('ix_videos_stufe', 'videos', ['stufe'], unique=False)
    op.create_index('ix_videos_veroeffentlicht', 'videos', ['veroeffentlicht'], unique=False)
    op.create_table('audios',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('video_id', sa.String(length=32), nullable=False),
    sa.Column('pfad', sa.String(length=500), nullable=False),
    sa.Column('format', sa.String(length=16), nullable=False),
    sa.Column('dauer_s', sa.Float(), nullable=True),
    sa.Column('groesse_bytes', sa.Integer(), nullable=True),
    sa.Column('abtastrate', sa.Integer(), nullable=True),
    sa.Column('kanaele', sa.Integer(), nullable=True),
    sa.Column('bezugsweg', sa.String(length=32), nullable=False),
    sa.Column('erstellt', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('video_id')
    )
    op.create_table('auftraege',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('art', sa.String(length=32), nullable=False),
    sa.Column('video_id', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('prioritaet', sa.Integer(), nullable=False),
    sa.Column('versuche', sa.Integer(), nullable=False),
    sa.Column('fortschritt', sa.Float(), nullable=False),
    sa.Column('meldung', sa.Text(), nullable=False),
    sa.Column('fehler', sa.Text(), nullable=False),
    sa.Column('parameter', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ergebnis', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('gestartet', sa.DateTime(timezone=True), nullable=True),
    sa.Column('beendet', sa.DateTime(timezone=True), nullable=True),
    sa.Column('herzschlag', sa.DateTime(timezone=True), nullable=True),
    sa.Column('erstellt', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_auftraege_status_art', 'auftraege', ['status', 'art'], unique=False)
    op.create_index('ix_auftraege_video', 'auftraege', ['video_id'], unique=False)
    op.create_table('transkripte',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('video_id', sa.String(length=32), nullable=False),
    sa.Column('engine', sa.String(length=64), nullable=False),
    sa.Column('modell', sa.String(length=120), nullable=False),
    sa.Column('sprache', sa.String(length=16), nullable=False),
    sa.Column('volltext', sa.Text(), nullable=False),
    sa.Column('segmente', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('dauer_verarbeitung_s', sa.Float(), nullable=True),
    sa.Column('aktuell', sa.Boolean(), nullable=False),
    sa.Column('erstellt', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_transkripte_video', 'transkripte', ['video_id'], unique=False)
    op.create_table('auftrag_protokoll',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('auftrag_id', sa.String(length=32), nullable=False),
    sa.Column('zeit', sa.DateTime(timezone=True), nullable=False),
    sa.Column('stufe', sa.String(length=8), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['auftrag_id'], ['auftraege.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_auftrag_protokoll_auftrag_zeit', 'auftrag_protokoll', ['auftrag_id', 'zeit'], unique=False)
    op.create_table('korrekturen',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('video_id', sa.String(length=32), nullable=False),
    sa.Column('transkript_id', sa.String(length=32), nullable=True),
    sa.Column('engine', sa.String(length=64), nullable=False),
    sa.Column('anbieter', sa.String(length=120), nullable=False),
    sa.Column('modell', sa.String(length=120), nullable=False),
    sa.Column('absaetze', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('themen', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('zusammenfassung', sa.Text(), nullable=False),
    sa.Column('aehnlichkeit', sa.Float(), nullable=True),
    sa.Column('bloecke_gesamt', sa.Integer(), nullable=False),
    sa.Column('bloecke_verworfen', sa.Integer(), nullable=False),
    sa.Column('dauer_verarbeitung_s', sa.Float(), nullable=True),
    sa.Column('manuell_bearbeitet', sa.Boolean(), nullable=False),
    sa.Column('aktuell', sa.Boolean(), nullable=False),
    sa.Column('erstellt', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['transkript_id'], ['transkripte.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_korrekturen_video', 'korrekturen', ['video_id'], unique=False)
    op.create_table('chunks',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('video_id', sa.String(length=32), nullable=False),
    sa.Column('korrektur_id', sa.String(length=32), nullable=True),
    sa.Column('reihenfolge', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('start_s', sa.Float(), nullable=False),
    sa.Column('end_s', sa.Float(), nullable=False),
    sa.Column('zeichen', sa.Integer(), nullable=False),
    sa.Column('thema', sa.Text(), nullable=False),
    sa.Column('ueberlappung_vor', sa.Integer(), nullable=False),
    sa.Column('ueberlappung_nach', sa.Integer(), nullable=False),
    sa.Column('manuell_bearbeitet', sa.Boolean(), nullable=False),
    sa.Column('erstellt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('aktualisiert', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['korrektur_id'], ['korrekturen.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('video_id', 'reihenfolge', name='uq_chunk_video_reihenfolge')
    )
    op.create_index('ix_chunks_video', 'chunks', ['video_id'], unique=False)
    op.create_table('einbettungen',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('chunk_id', sa.String(length=32), nullable=False),
    sa.Column('anbieter', sa.String(length=120), nullable=False),
    sa.Column('modell', sa.String(length=120), nullable=False),
    sa.Column('dimension', sa.Integer(), nullable=False),
    sa.Column('vektor', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=False),
    sa.Column('erstellt', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chunk_id', 'modell', name='uq_einbettung_chunk_modell')
    )
    op.create_index('ix_einbettungen_modell', 'einbettungen', ['modell'], unique=False)
    # ### end Alembic commands ###


    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_einbettungen_vektor_hnsw ON einbettungen "
        "USING hnsw (vektor vector_cosine_ops) WITH (m = 16, ef_construction = 96)"
    )


def downgrade() -> None:
    op.execute("DROP INDEX IF EXISTS ix_einbettungen_vektor_hnsw")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_einbettungen_modell', table_name='einbettungen')
    op.drop_table('einbettungen')
    op.drop_index('ix_chunks_video', table_name='chunks')
    op.drop_table('chunks')
    op.drop_index('ix_korrekturen_video', table_name='korrekturen')
    op.drop_table('korrekturen')
    op.drop_index('ix_auftrag_protokoll_auftrag_zeit', table_name='auftrag_protokoll')
    op.drop_table('auftrag_protokoll')
    op.drop_index('ix_transkripte_video', table_name='transkripte')
    op.drop_table('transkripte')
    op.drop_index('ix_auftraege_video', table_name='auftraege')
    op.drop_index('ix_auftraege_status_art', table_name='auftraege')
    op.drop_table('auftraege')
    op.drop_table('audios')
    op.drop_index('ix_videos_veroeffentlicht', table_name='videos')
    op.drop_index('ix_videos_stufe', table_name='videos')
    op.drop_index('ix_videos_serie_folge', table_name='videos')
    op.drop_table('videos')
    op.drop_index('ix_nachrichten_unterhaltung', table_name='nachrichten')
    op.drop_table('nachrichten')
    op.drop_table('unterhaltungen')
    op.drop_table('quellen')
    op.drop_table('einstellungen')
    op.drop_table('anbieter')
    # ### end Alembic commands ###
